version: '3'
services:
  container_a:
    image: container_a
    build:
      context: ./Container_A
      dockerfile: Dockerfile
    container_name: container_a  # Custom container name
    ports:
      - "8000:8000"
    volumes:
      - ./Container_A:/app
    networks:
      - Interpol
    depends_on:
      - container_c

  container_c:
    image: rabbitmq:management
    container_name: container_c
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5673:5672"
      - "15672:15672"
    networks:
      - Interpol

networks:
  Interpol:
    driver: bridge
