"""Add image_url column to Person table

Revision ID: 17860ae97c2d
Revises: 
Create Date: 2023-07-21 16:05:45.554752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17860ae97c2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('entity_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.alter_column('image',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('entity_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
